### ISSUE TITLE
Input Dialog not work

### ISSUE THREAD

**Issue by mustii82** [TomGrill/gdx-dialogs#21]
Exception in thread "Thread-2" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:673)
	at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630)
	at com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JOptionPane.setUI(JOptionPane.java:1860)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
	at de.tomgrill.gdxdialogs.desktop.dialogs.DesktopGDXTextPrompt$1.run(DesktopGDXTextPrompt.java:76)
	at java.lang.Thread.run(Thread.java:745)

I get always this Error on 1.2.3 when I want to show a TextInput Dialog on Desktop

**Comment by mustii82** [comment]
But it works on 1.2.1

**Comment by TomGrill** [comment]
Cannot reproduce this error. Everything working fine here.
Can you provide output of `java -version`?

**Comment by mustii82** [comment]
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by mustii82** [comment]
Even with the newest Java update I get the same error

**Comment by TomGrill** [comment]
Maybe its an Mac problem:
at com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53)
I look it up on a mac when I get access to

**Comment by mustii82** [comment]
Okay it worked for me thank you :)

**Comment by TomGrill** [comment]
Ok this is actually a bug, fixed in 1.2.5. Thanks
