### ISSUE TITLE
No OpenGL context found in the current thread. On setScreen();

### ISSUE THREAD

**Issue by mustii82** [TomGrill/gdx-dialogs#5]
If I call setScreen(); in a dialog o'clock function I get this error:

Exception in thread "Thread-1" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL20.glCreateShader(GL20.java:219)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glCreateShader(LwjglGL20.java:201)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.loadShader(ShaderProgram.java:207)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.compileShaders(ShaderProgram.java:186)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:169)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:156)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:120)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:73)

**Comment by TomGrill** [comment]
Dialogs run in another thread to prevent game in background from stopping while a dialog is active.

To use methods which require OpenGL context:

```
dialog.setClickListener(new ButtonClickListener() {
	@Override
	public void click(int button) {
		Gdx.app.postRunnable(new Runnable() {
			@Override
			public void run() {
				// switch screen here
			}
		});
	}
});
```
